### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by dhasilin** [jamesward/hello-springboot#2]
* What went wrong:
       A problem occurred configuring root project 'hello-springboot'.
       > Could not resolve all dependencies for configuration ':classpath'.
          > Could not resolve gradle.plugin.com.jamesward:atom-gradle-plugin:0.0.1.

So it's not building anymore :(

**Comment by jamesward** [comment]
Hmm...  The plugin comes from the Gradle Plugin repo and I'm not sure why it would disappear from there.  But I've updated everything in this repo to the latest and it seems to be working fine.  Can you give the latest a try?

**Comment by dhasilin** [comment]
Fixed, thank you :)
