### ISSUE TITLE
Stage question

### ISSUE THREAD

**Issue by dhasilin** [jamesward/hello-springboot#3]
Hi,
this example is working :)
 I'm just not sure how stage is done.
It looks like in stage task we just build app and in proc file we run it from "buils/libs/jarName.jar"

But for my project it seems that there is no jar in build/libs (I have multimodule project)
What I found about that: http://stackoverflow.com/questions/26389679/running-spring-app-built-with-gradle-on-heroku

It looks like I need to copy jar file to some other place. Do you have any idea why is that ?

**Comment by jamesward** [comment]
I don't think you should need to copy jar files around.  For me it works to just run the `build` task which generates the `build/libs/hello-springboot.jar` file.  Heroku runs the `stage` task so that needs to be defined as:
```
task stage {
    dependsOn build
}
```

There is just one caveat with this...  When the build runs on Heroku there is a different root directory name.  And by default Gradle uses the root directory name as the project name, and thus the jar name.  So I override that in the `settings.gradle` file:
```
rootProject.name = 'hello-springboot'
```

I hope that helps.

**Comment by dhasilin** [comment]
Issue for me is that I have multiproject gradlew build so I hva follwong stage task:

```
evaluationDependsOnChildren();

task stage{
    dependsOn subprojects.build
}

task clean {
    dependsOn subprojects.clean
}

stage.mustRunAfter(clean)
```

And after that in Prrocfile im pointing to web project:

`web: java -Dserver.port=$PORT -jar web/build/libs/name-0.1.jar`

And it works locally but after push I get green build and follwing error: 
` Error: Unable to access jarfile web/build/libs/name-0.1.jar`

**Comment by jamesward** [comment]
Did you set the `rootProject.name` in `settings.gradle`?

**Comment by jamesward** [comment]
BTW, you can debug this by running: `heroku run bash` and then looking through the filesystem that was created via the buildpack.

**Comment by dhasilin** [comment]
No, but jar name is set in build.gradle for web project:
```
jar {
	baseName = 'name'
	version = '0.1'
}
```

So thats why I know name and use it in Procfile.
but, I will try to set it maybe by some magic on Heroku it gets different name

**Comment by dhasilin** [comment]
heroku run bash - That was what I really NEED to know - thank you very much :)
For some reason on heroku  Ive expect:   name-0.1.jar but it was name-0.0.1-SNAPSHOT.jar

**Comment by dhasilin** [comment]
Fixed, and works, Thank you very much :)
